<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
<ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
	<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.2" />
    <PackageReference Include="Serilog.AspNetCore" Version="6.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.13" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.15.0" />
	<PackageReference Include="Google.Protobuf" Version="3.21.9" />
	<PackageReference Include="Google.Protobuf.Tools" Version="3.21.9" />
	<PackageReference Include="Grpc" Version="2.46.5" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.40.0" />
	<PackageReference Include="Grpc.Tools" Version="2.50.0">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.0" />
</ItemGroup>
<ItemGroup>
  <ProjectReference Include="..\LivrEtec\LivrEtec.csproj" />
</ItemGroup>
</Project>
