// <auto-generated />
using System;
using LivrEtec;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LivrEtec.Migrations
{
    [DbContext(typeof(PacaContext))]
    [Migration("20221115032559_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LivrEtec.Aluno", b =>
                {
                    b.Property<int>("Cd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.HasKey("Cd");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("LivrEtec.Autor", b =>
                {
                    b.Property<int>("cd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Livrocd")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("cd");

                    b.HasIndex("Livrocd");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("LivrEtec.Emprestimo", b =>
                {
                    b.Property<int>("Cd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlunoCd")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FimDataEmprestimo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Livrocd")
                        .HasColumnType("int");

                    b.HasKey("Cd");

                    b.HasIndex("AlunoCd");

                    b.HasIndex("Livrocd");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("LivrEtec.Livro", b =>
                {
                    b.Property<int>("cd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Arquivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("cd");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("LivrEtec.Tag", b =>
                {
                    b.Property<int>("Cd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Livrocd")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Cd");

                    b.HasIndex("Livrocd");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("LivrEtec.Autor", b =>
                {
                    b.HasOne("LivrEtec.Livro", null)
                        .WithMany("Autores")
                        .HasForeignKey("Livrocd");
                });

            modelBuilder.Entity("LivrEtec.Emprestimo", b =>
                {
                    b.HasOne("LivrEtec.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoCd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivrEtec.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("Livrocd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("LivrEtec.Tag", b =>
                {
                    b.HasOne("LivrEtec.Livro", null)
                        .WithMany("Tags")
                        .HasForeignKey("Livrocd");
                });

            modelBuilder.Entity("LivrEtec.Livro", b =>
                {
                    b.Navigation("Autores");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
