[package]
name = "livretec_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
datetime = "0.5.2"

tokio =  { version = "1.0", features = ["rt-multi-thread", "macros"] }
prost = "0.11"
prost-types = "0.11.9"
tonic = "0.9.2"
mysql = "*"

[build-dependencies]
tonic-build = "0.9.2"