global using LivrEtec.Models;
global using LivrEtec.Services;
global using LivrEtec.Servidor.BD;
global using LivrEtec.Servidor.Repositorios;
global using LivrEtec.Servidor.Services;
global using LivrEtec.Testes.Doubles;
global using LivrEtec.Testes.Utilitarios;
global using Xunit;
global using DTO = LivrEtec.GIB.DTO;
global using LEM = LivrEtec.Models;
