version: "3.9"

services:
  gib_servidor: 
    container_name: "livretec_gib_servidor"
    image: livretec_gib_servidor
    profiles: [teste, backend]
    build:
      context: .
      dockerfile: ./Docker/GIB.Servidor/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5259:5259
  testes: 
    container_name: "livretec_testes"
    image: livretec_testes
    profiles: [teste]
    build:
      context: .
      dockerfile: ./Docker/Testes/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      gib_servidor: 
        condition: service_started

  db:
    container_name: "livretec_bd"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: LivrEtecBD    
      MYSQL_USER: LivrEtecServe
      MYSQL_PASSWORD: LivrEtecSenha
    volumes: 
      - livretec-mysql-volume:/var/lib/mysql
    ports:
      - 42333:3306
    healthcheck:
      test: mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD -e "select 'esta funcionando'" $$MYSQL_DATABASE
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

volumes:
  livretec-mysql-volume: