/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RequestLogin"];
                    "text/json": components["schemas"]["RequestLogin"];
                    "application/*+json": components["schemas"]["RequestLogin"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseLogin"];
                        "application/json": components["schemas"]["ResponseLogin"];
                        "text/json": components["schemas"]["ResponseLogin"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/autorizado/{id_permissao}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id_permissao: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/usuario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Usuario"];
                        "application/json": components["schemas"]["Usuario"];
                        "text/json": components["schemas"]["Usuario"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/usuario/{login}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    login: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emprestimos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    IdLivro?: number;
                    IdPessoa?: number;
                    Fechado?: boolean;
                    Atrasado?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Emprestimo"][];
                        "application/json": components["schemas"]["Emprestimo"][];
                        "text/json": components["schemas"]["Emprestimo"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RequestAbrirEmprestimo"];
                    "text/json": components["schemas"]["RequestAbrirEmprestimo"];
                    "application/*+json": components["schemas"]["RequestAbrirEmprestimo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emprestimos/devolver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RequestDevolverEmprestimo"];
                    "text/json": components["schemas"]["RequestDevolverEmprestimo"];
                    "application/*+json": components["schemas"]["RequestDevolverEmprestimo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/emprestimos/prorrogar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RequestProrrogarEmprestimo"];
                    "text/json": components["schemas"]["RequestProrrogarEmprestimo"];
                    "application/*+json": components["schemas"]["RequestProrrogarEmprestimo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/emprestimos/perda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RequestPerdaEmprestimo"];
                    "text/json": components["schemas"]["RequestPerdaEmprestimo"];
                    "application/*+json": components["schemas"]["RequestPerdaEmprestimo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/emprestimos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    NomeLivro?: string;
                    NomeAutor?: string;
                    IdTags?: number[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Livro"][];
                        "application/json": components["schemas"]["Livro"][];
                        "text/json": components["schemas"]["Livro"][];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Livro"];
                    "text/json": components["schemas"]["Livro"];
                    "application/*+json": components["schemas"]["Livro"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Livro"];
                    "text/json": components["schemas"]["Livro"];
                    "application/*+json": components["schemas"]["Livro"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livros/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Livro"];
                        "application/json": components["schemas"]["Livro"];
                        "text/json": components["schemas"]["Livro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Nome?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Tag"][];
                        "application/json": components["schemas"]["Tag"][];
                        "text/json": components["schemas"]["Tag"][];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Tag"];
                    "text/json": components["schemas"]["Tag"];
                    "application/*+json": components["schemas"]["Tag"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Tag"];
                    "text/json": components["schemas"]["Tag"];
                    "application/*+json": components["schemas"]["Tag"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Tag"];
                        "application/json": components["schemas"]["Tag"];
                        "text/json": components["schemas"]["Tag"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Autor: {
            /** Format: int32 */
            id?: number;
            nome?: string | null;
        };
        Cargo: {
            /** Format: int32 */
            id?: number;
            nome?: string | null;
            permissoes?: components["schemas"]["Permissao"][] | null;
        };
        Emprestimo: {
            /** Format: int32 */
            id?: number;
            atrasoJustificado?: boolean | null;
            comentario?: string | null;
            /** Format: date-time */
            dataEmprestimo?: string;
            /** Format: date-time */
            dataFechamento?: string | null;
            devolvido?: boolean | null;
            explicacaoAtraso?: string | null;
            fechado?: boolean;
            /** Format: date-time */
            fimDataEmprestimo?: string;
            livro?: components["schemas"]["Livro"];
            pessoa?: components["schemas"]["Pessoa"];
            usuarioCriador?: components["schemas"]["Usuario"];
            usuarioFechador?: components["schemas"]["Usuario"];
        };
        Livro: {
            /** Format: int32 */
            id?: number;
            nome?: string | null;
            arquivado?: boolean;
            descricao?: string | null;
            /** Format: int32 */
            quantidade?: number;
            autores?: components["schemas"]["Autor"][] | null;
            tags?: components["schemas"]["Tag"][] | null;
        };
        Permissao: {
            /** Format: int32 */
            id?: number;
            nome?: string | null;
            descricao?: string | null;
            permissoesDependete?: components["schemas"]["Permissao"][] | null;
        };
        Pessoa: {
            /** Format: int32 */
            id?: number;
            nome?: string | null;
            telefone?: string | null;
        };
        RequestAbrirEmprestimo: {
            /** Format: int32 */
            idPessoa?: number;
            /** Format: int32 */
            idLivro?: number;
        };
        RequestDevolverEmprestimo: {
            /** Format: int32 */
            idEmprestimo?: number;
            atrasoJustificado?: boolean | null;
            explicacaoAtraso?: string | null;
        };
        RequestLogin: {
            login?: string | null;
            hashSenha?: string | null;
        };
        RequestPerdaEmprestimo: {
            /** Format: int32 */
            id?: number;
        };
        RequestProrrogarEmprestimo: {
            /** Format: int32 */
            idEmprestimo?: number;
            /** Format: date-time */
            novaData?: string;
        };
        ResponseLogin: {
            jwtToken?: string | null;
        };
        Tag: {
            /** Format: int32 */
            id?: number;
            nome?: string | null;
        };
        Usuario: {
            /** Format: int32 */
            id?: number;
            nome?: string | null;
            cargo?: components["schemas"]["Cargo"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
