name: Docker Compose 

on:
  push:
    branches: [ "main" , "Desenvolvimento" ]
  pull_request:
    branches: [ "main" , "Desenvolvimento" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: "src"
    steps:
    - uses: actions/checkout@v3
    - name: Up Docker Images
      run: docker compose up --build
