name: Docker Compose 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: "src"
    steps:
    - uses: actions/checkout@v3
    - name: Up Docker Images
      run:  docker compose -p livretec --profile teste up --build --exit-code-from testes
