# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env: 
      APP_SETTINGS_JSON_PATH: '${{ github.workspace }}/src/appsettings.json'
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: "src"
    steps:  
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup MySQL 
      uses: mirromutth/mysql-action@v1.1
      with: 
        mysql root password: root 
        mysql database: LivrEtecBD 
        mysql user: LivrEtecServe 
        mysql password: LivrEtecSenha 

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal